name: Test, Build and Push
on:
  push: # enabling push event on main branch to fire the workflow
    branches:
      - main
jobs:
  job1:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' 
      - name: Install requirements.txt
        run: pip install -r requirements.txt
      - name: Run Tests
        run: python -m pytest
      
  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
    - uses: actions/checkout@v3
    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: shprakas/rps-amd64
        tags:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
