name: Test, Build and Push
on:
  push: # enabling push event on main branch to fire the workflow
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest # runs on docker container running ubuntu
    
    steps:
      - uses: actions/checkout@v3 # Checkout repo
      - name: Set up python 3.9
        uses: actions/setup-python@v4 # Installs python3.9
        with:
          python-version: '3.9' 
      - name: Install requirements.txt # Installs all packages present in requirememnts.txt
        run: pip install -r requirements.txt
      - name: Run Tests # Runs the test
        run: make test
 
  # Build and push dcoker image to docker.io     
  build_push:
    runs-on: ubuntu-latest
    needs: [test] # Build and push image only if test pass
    steps:
    - uses: actions/checkout@v3
    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4 # Recommended image on github action page for buulding and pushing docker image
      with:
        image: shprakas/rps-amd64 # Image name
        addLatest: true
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }} # Dockerhub credentials
        password: ${{ secrets.DOCKER_PASSWORD }}
